### ISSUE TITLE
Stuck at downloading 

### ISSUE THREAD

**Issue by Hyllesen** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#10]
I'm stuck with downloading, when I select "Download whooole course" for example, there's no visual feedback.

**Comment by Ebram-Tharwat** [comment]
Normally, for every video, there should be a progress bar, either you clicked "Download the whooole course!", "Download all module clips".
@Hyllesen , can you please describe which behavior happens to you? Do the videos even get downloaded?
