### ISSUE TITLE
The remote server returned an error: (417) Expectation failed.

### ISSUE THREAD

**Issue by mortezadalil** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#11]
This error Happened on line 199 (courseController)  
 var response = httpWebRequest.GetResponse();
could you help me with this error?
![image](https://cloud.githubusercontent.com/assets/15077932/18652403/866eaf76-7ee7-11e6-95c2-4a71e81027de.png)

**Comment by Ebram-Tharwat** [comment]
This error means that the path probably contains invalid characters.
Can you please try to debug and check the folder/file names?

**Comment by mortezadalil** [comment]
I changed local path in web.config and also selected different courses  but always "The remote server returned an error: (417) Expectation failed." happened in this line :
var response = httpWebRequest.GetResponse();

**Comment by Ebram-Tharwat** [comment]
That's strange, because no one reported this error before.
Can you please try [the solution provided here on StackOverflow](http://stackoverflow.com/a/7358457/1295905), and let me know if that solved your problem.

**Comment by mortezadalil** [comment]
Worked with this solution!
