### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by AhmadBehzadi** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#14]
Hi,
when I try to download any video give this error.

> The remote server returned an error: (400) Bad Request.

I'm sure the username and password in the web.config is valid and has access (Because in the Pluralsight website I can see the same video)
I traced the code and error was occurred at the following line:

```
GetClipUrl(ClipToSave clip)
{
    ...
    using (var response = http.GetResponse())
    ...
}
```

Also checked the cookie in this method
```
    if (!clip.UserMayViewClip)
         SetupAuthenticationCookie(http);
```

and it was something like this:

`eyJ0eXAiziJKV1QiLCJ2bGciOiJIUzI1NiJ9.eyJoYW5kbHUiOiIdNjBlYTlvZC02OWZlLTIzZDMtOTg0ZS0zMDNiMjhl5TI4NGUiLCJpYXQiOjE0NzU5MDE5NzQsI0V4cCI6MTQ3NjUwNjc3NH0.ekjrWY9T1J5ALgsQZccYqNl-u8fZvYw9pctwuGkAorM; domain=.pluralsight.com; expires=Sat, 15-Oct-2016 04:46:14 GMT; path=/; secure; HttpOnly,www-status-production=1; domain=.pluralsight.com; expires=Sat, 15-Oct-2016 04:46:14 GMT; path=/; secure`

Any suggestion ?

**Comment by Ebram-Tharwat** [comment]
@AhmadBehzadi , can you please post the video url, which you are trying to download?

**Comment by AhmadBehzadi** [comment]
@Ebram-Tharwat , Sure. 
I searched [this course](https://app.pluralsight.com/library/courses/css-intro) :
`https://app.pluralsight.com/library/courses/css-intro`
And tried to download the first clip of first module.

**Comment by Ebram-Tharwat** [comment]
@AhmadBehzadi, I have tried to download your course, and it works fine with me. I thought there might be an error during parsing URL or invalid course name, but all seems good.

Now, do you hold a valid premium account(i mean, do you actually able to see the videos in normal way)?. When i tried with expired account, I got the same error.
Also, do you get this error only with this course, or with any course(even free ones)?

**Comment by AhmadBehzadi** [comment]
@Ebram-Tharwat, Thanks for your effort. I don't know what was wrong,I searched and found this method and replaced it with yours.

```
        private const string ClipDetailsUrl = "http://app.pluralsight.com/training/Player/ViewClip";
        private const string UserAgentString = @"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36";

        public string GetClipLocation(string playerParameters, string cookie)
        {
            var clipDetails = (HttpWebRequest)WebRequest.Create(new Uri(ClipDetailsUrl));
            clipDetails.Accept = "application/json";
            clipDetails.ContentType = "application/json";
            clipDetails.Method = "POST";
            clipDetails.UserAgent = UserAgentString;
            clipDetails.Headers.Add("Cookie", cookie);

            var playerParameterQuery = HttpUtility.ParseQueryString(playerParameters);
            var playerParameterQueryObject = new
            {
                a = playerParameterQuery["author"],
                m = playerParameterQuery["name"],
                course = playerParameterQuery["course"],
                cn = playerParameterQuery["clip"],
                mt = "mp4",
                q = "1024x768",
                cap = false,
                lc = "en"
            };

            var encoding = new ASCIIEncoding();
            var dataBytes = encoding.GetBytes(JsonConvert.SerializeObject(playerParameterQueryObject));

            var sendStream = clipDetails.GetRequestStream();
            sendStream.Write(dataBytes, 0, dataBytes.Length);
            sendStream.Close();

            var response = clipDetails.GetResponse();
            var receiveStream = response.GetResponseStream();
            var sr = new StreamReader(receiveStream);
            var content = sr.ReadToEnd();

            return content;
        }

```
I didn't check it what is exactly different, but it's working now.

**Comment by Ebram-Tharwat** [comment]
@AhmadBehzadi , glad you managed to solve it.

I check the differences and the changes that I found so far:

1. `UserAgent`
   - My value, `Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
   - Your value, `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36`

1. Setting authentication token early(which I don't think would different effect).

Can you please post where you found this solution? Thanks.

**Comment by AhmadBehzadi** [comment]
Yes, from [here](https://github.com/cmeegamarachchi/PluralsightDownloader/blob/master/PluralsightDownloader.Service/PluralsightDownloaderService.cs#L76)

@Ebram-Tharwat I've created a new winform application that does what you did + some changes and options !
Can I share it in github?

**Comment by Ebram-Tharwat** [comment]
@AhmadBehzadi , Yes sure.

Any contribution is welcomed. I would just ask you to mention my project(e.g URL) in your winform application.

**Comment by AhmadBehzadi** [comment]
@Ebram-Tharwat [This ](https://github.com/AhmadBehzadi/WinForm-Pluralsight-Video-Downloader)is my app. If you like it, can mention it in your readme.md.
Thanks

**Comment by nmquan-dev** [comment]
@AhmadBehzadi I've downloaded your project, but it reported Login Faile. Help Me!!!!
var loginRequestData = encoding.GetBytes($"Username={userName}&Password={password}"); 
Error	1	Unexpected character '$'
