### ISSUE TITLE
Make it simply to run

### ISSUE THREAD

**Issue by rohmanhm** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#15]
Hi Ebram, I didn't have installation of **Visual Studio** or **ASP.NET Server** in my computer. Can you make this simple to run without install VS or ASP.NET server? Like just open the website in my browser.

Thanks

**Comment by davidlav** [comment]
Yes, I'd like to use this but I have no idea how to run it.  Could you put instructions in your readme?  Thanks!

**Comment by Ebram-Tharwat** [comment]
@rohmanhm , @davidlav , thank you much for your feedback.

I was thinking of turning this app into NodeJS app as it would only require changing the back-end code. Then, we can go further step, and build an [electron app](http://electron.atom.io/) over it.

What you think? I'm looking forward to feedback.

**Comment by davidlav** [comment]
Sounds cool!

**Comment by Ebram-Tharwat** [comment]
@davidlav , please check #9 for instructions on how to run the app.

**Comment by xlight05** [comment]
@Ebram-Tharwat 
Would be great if you can do it with Node JS. Its really hard to run this with horrible internet connections
