### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by KatteKwaad** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#16]
Hey Ebram,

I'm not sure whether the pluralsight api url's have changed but getting a 400 bad request after getting my authentication cookie back. I believe the authentication was a success so are you guys still able to get vids downloaded?

Thanks
Mike

**Comment by Ebram-Tharwat** [comment]
@KatteKwaad, can you please post the video url, which you are trying to download? And, do you get this error only with this course, or with any course(even free ones)?

Also, can you please check issue #14 , maybe it's the same issue.

**Comment by KatteKwaad** [comment]
Hmm I think the issue was actually nothing to do with the urls or code but the account that I used. I just noticed that it expired on Friday last week.

Using a newer one works. It would have been nice if the Pluralsight api returned a 401 instead of 400 :)
