### ISSUE TITLE
Tutorial needed

### ISSUE THREAD

**Issue by MYounas** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#17]
Hi,Man you did great job I am 2nd year student doing BS in Software engineering,Sorry for Creating new issue for a silly request,Please can you refer any tutorial to make this type of downloader.
and you didn't mention your email aur any social networking account for contact,So I create new Issue sorry for that.
Thanx in advance.

**Comment by MYounas** [comment]
Or you can mail me @ younus.ubit56@gmail.com

**Comment by Ebram-Tharwat** [comment]
@MYounas , you are welcome, and i apologize for late reply.

Regarding the tutorial, I don't know if there is a suitable tutorial for that. For this project, I first identified what i need to build it as a components then google it. For example, I needed to mimic the login screen, so I searched for how to submit a form using C# code or `WebClient`. Then, I got a video URL so, I searched for how to download file.

Kindly read this part [the-idea-of-the-project](https://github.com/Ebram-Tharwat/CSharp-Pluralsight-Downloader#the-idea-of-the-project).

Finally, I hope that helped you. If you still need more help, you are totally welcome to ask anything.

**Comment by MYounas** [comment]
How you go through all of the links in a course?

**Comment by Ebram-Tharwat** [comment]
video links? through `PluralSight API`.
When you select/navigate to/watch any course, inspect the network panel and hence you will learn more about their API. And of course you can use a tool like `fiddler`.

**Comment by MYounas** [comment]
Ohk got that.Thanx man
