### ISSUE TITLE
Remote server returned error. 400 bad request.

### ISSUE THREAD

**Issue by xlight05** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#18]
First, I must say this is a extremely useful tool and thank you so much for making it this far.
for the issue,
I have two accounts, 2 pcs and 2 connection and I'm getting same errors on all those accounts.
http://image.prntscr.com/image/e2a03755f02e4bf38f2037ec5cfd9082.png

I think its not just for me,  They patched it?  I can manually view videos btw

edit : Down loader is working for most cases but not for this 
https://app.pluralsight.com/library/courses/ccna-intro-networking

Checked several courses in that CCNA path and non of them worked.

**Comment by Ebram-Tharwat** [comment]
I tried downloading your course ["ccna-intro-networking"](https://app.pluralsight.com/library/courses/ccna-intro-networking), and it works fine.
Are you sure about your credentials? Also, check the following closed issues: #14 and #16 .

If you still facing issue, can you please try to debug and check which line causes the error. 

Thanks for your feedback.

**Comment by xlight05** [comment]
Sorry for late reply,
I am using this script on my home pc (win 7) and my vps (windows server 2012 r2) using two different accounts and facing the same issue just for that learning path.tbh I have no clue how I'm the only one who facing this issue. Both accounts are working just fine and I completed downloading Network + course after I face this issue too. Had no problem with that.
Tbh I have no experience coding or debugging so I'm afraid I can't touch those files.If there are any way that I can contact you directly I can give you access to my VPS so you can take a look there.

**Comment by Ebram-Tharwat** [comment]
@xlight05 , no problem. I tried the same video "IP Addresses and MAC Addresses", and I got the same error.

The issue is related to video quality parameter. I working on it now

**Comment by xlight05** [comment]
@Ebram-Tharwat Thanks for working on it. Good luck with it

**Comment by Ebram-Tharwat** [comment]
@xlight05 , here you go. You can now update the project files and try downloading after applying the fix.

I have added a new request to choose the proper format to download course's videos. Also, I added a logging capability so that if you got an error during running the app, we can check the log file to see what went wrong.

Finally, I would appreciate if you give me your feedback after this fix, to make sure that nothing is broken.

**Comment by xlight05** [comment]
I just tried downloading all the courses I was unable to, and it completely works.Thanks alot for your great job ;)
