### ISSUE TITLE
Forbidden access!?

### ISSUE THREAD

**Issue by ba18545** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#21]
I have valid account and I can successfully logged in in Pluralsight website, but not here?!

**Comment by Ebram-Tharwat** [comment]
@ba18545 , can you tell me what the exact behavior/error you get?. If you are using the latest updates, can you share the log file?

Also, have you tried to debug the code and see the origin of this issue ?

**Comment by ba18545** [comment]
@Ebram-Tharwat  The problem was because I don't have access on Exercise files , i just commented this two lines, and is working fine now.
`//json = webClient.DownloadString(string.Format(Constants.COURSE_EXERCISE_FILES_URL, coursename));
 //course.ExerciseFiles = JsonConvert.DeserializeObject<ExerciseFiles>(json);`

**Comment by Ebram-Tharwat** [comment]
@ba18545 , so you can access and download the videos but not the _exercise files_ ?! Or there aren't any exercise files, so the app is trying to download something that doesn't exist? 

Can you please give me your feedback, and also which course you were trying to download. Thank you

**Comment by ba18545** [comment]
@Ebram-Tharwat Yes i can download videos but not exercise files, because my subscription doesn't include exercise files. It happens with all courses.

**Comment by Ebram-Tharwat** [comment]
@ba18545  , which course you were trying to download?
