### ISSUE TITLE
Sequence contains more than one matching element 

### ISSUE THREAD

**Issue by xlight05** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#22]
http://image.prntscr.com/image/92232fbbc49c48108408e8fa74329a45.png
http://image.prntscr.com/image/7c58c37a50cb4b68a2974d1d96f61a3f.png

Course link - 
https://app.pluralsight.com/library/courses/introduction-to-machine-learning-encog/

any clue?

**Comment by Ebram-Tharwat** [comment]
@xlight05 , please update the project files and try again.

The issue with that course is in setting subtitles for the videos. In the ninth module, you will find there are two videos with the same name `Flow Chart` and that's caused the exception.

Finally, try again after updating and please give me your feedback either for this course or other courses.
