### ISSUE TITLE
Subtitle issue

### ISSUE THREAD

**Issue by minhhungit** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#24]
Can we change download subtitle option to true as default value, and check if it has no subtitle, we don't need to download it

**Comment by xlight05** [comment]
Not everyone needs subtitles. Only people who have bad English requires subtitles.(Me as a example). Not everyone needs to spam their files with .str files. I think 'false' is better for the default value.Again, for your second suggestion, you can easily check weather subtitles are available or not by one click. its not really a big deal in my opinion. correct me if I'm wrong.

**Comment by minhhungit** [comment]
ok @xlight05 :)
