### ISSUE TITLE
Issue Downloading Clip

### ISSUE THREAD

**Issue by coreil40** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#26]
Hello,
I have an error when I tried to download a clip.
"couldn't retrieve clip URL. Please check log file."

Log file:

2016-12-21 18:43:36.2321 TRACE System.Exception: Couldn't retrieve clip URL. Please check log file.
   at PluralsightDownloader.Web.Controllers.CourseController.GetClipUrl(ClipToSave clip) in c:\Users\MMORDJANE\Downloads\CSharp-Pluralsight-Downloader-master\PluralsightDownloader.Web\Controllers\CourseController.cs:line 227
   at PluralsightDownloader.Web.Controllers.CourseController.<DownloadCourseModuleClip>d__d.MoveNext() in c:\Users\MMORDJANE\Downloads\CSharp-Pluralsight-Downloader-master\PluralsightDownloader.Web\Controllers\CourseController.cs:line 86
 ------------------------------------------------------------

Regards,

**Comment by Ebram-Tharwat** [comment]
@coreil40 , can you please post which course you were trying to download. More importantly, are you sure you have valid credentials and you can watch course videos normally through Pluralsight website.

**Comment by coreil40** [comment]
Hello ,

Many thanks for your reply , I have a valid credentials I can download clip
with pluralsight android application (I have downloaded 10 courses on my
smartphones).

I tried to download Mvc4 course (mentionned as an example in the
application ).

When I got the error I tried with other courses but I get the same error.
I have launched application on Firefox and Edge.

Regards.
M.MORDJANE

Le 21 déc. 2016 19:20, "Ebram Khalil" <notifications@github.com> a écrit :

@coreil40 <https://github.com/coreil40> , can you please post which course
you were trying to download. More importantly, are you sure you have valid
credentials and you can watch course videos normally through Pluralsight
website.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Ebram-Tharwat/CSharp-Pluralsight-Downloader/issues/26#issuecomment-268599944>,
or mute the thread

**Comment by Ebram-Tharwat** [comment]
@coreil40 , I just tried on my machine and it works just fine. Do you have the latest version?

Can you please share the whole log file? It don't save any sensitive data in it. Also, is that the first time that you use the app, or it was working and suddenly stop?

**Comment by coreil40** [comment]
I'm using the app for the first time , I can see all the course structure
but when I click on download I get this error.

I downloaded the zip file today from
Github website, I guess it's the last version.

Now I'm using my phone for sending email , log file is on my laptop I will
send it to you ASAP.

Thanks.

Le 21 déc. 2016 20:03, "Ebram Khalil" <notifications@github.com> a écrit :

@coreil40 <https://github.com/coreil40> , I just tried on my machine and it
works just fine. Do you have the latest version?

Can you please share the whole log file? It don't save any sensitive data
in it. Also, is that the first time that you use the app, or it was working
and suddenly stop?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Ebram-Tharwat/CSharp-Pluralsight-Downloader/issues/26#issuecomment-268611071>,
or mute the thread

**Comment by coreil40** [comment]
Attached log file.
---------- Message transféré ----------
De : "mustapha mordjane" <mordjane@gmail.com>
Date : 21 déc. 2016 20:09
Objet : Re: [Ebram-Tharwat/CSharp-Pluralsight-Downloader] Issue Downloading
Clip (#26)
À : "Ebram-Tharwat/CSharp-Pluralsight-Downloader" <
reply@reply.github.com
>
Cc :

I'm using the app for the first time , I can see all the course structure
but when I click on download I get this error.

I downloaded the zip file today from
Github website, I guess it's the last version.

Now I'm using my phone for sending email , log file is on my laptop I will
send it to you ASAP.

Thanks.

Le 21 déc. 2016 20:03, "Ebram Khalil" <notifications@github.com> a écrit :

@coreil40 <https://github.com/coreil40> , I just tried on my machine and it
works just fine. Do you have the latest version?

Can you please share the whole log file? It don't save any sensitive data
in it. Also, is that the first time that you use the app, or it was working
and suddenly stop?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Ebram-Tharwat/CSharp-Pluralsight-Downloader/issues/26#issuecomment-268611071>,
or mute the thread

**Comment by Ebram-Tharwat** [comment]
@coreil40 , i don't see the attached log. Did you have problem adding it to your comment? or you have solved the issue

**Comment by nmquan-dev** [comment]
@Ebram-Tharwat Hi, I just want to download subtitles of Course. But I don't know do that, Please help me!!! Thanks for the support!

**Comment by Ebram-Tharwat** [comment]
@nmquan-dev , have you set **SUBTITLES** to `true` in **Web.config** ?

**Comment by nmquan-dev** [comment]
@Ebram-Tharwat  I just want to download subtitles of Course but don't download the video clip. 
Tks!!!

**Comment by Ebram-Tharwat** [comment]
@nmquan-dev , then you will have to **comment** manually the code which download the video clip.

**Comment by nmquan-dev** [comment]
@Ebram-Tharwat Thanks for the support!!!!

**Comment by Ebram-Tharwat** [comment]
@coreil40 , do you use special characters in your password or username? 

Someone else has the same issue, check #27
