### ISSUE TITLE
Invalid Username or Password

### ISSUE THREAD

**Issue by fabercs** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#27]
I've tried to dl a course by using my valid account, but it gives the error "invalid username or password".
When i debug, i see auth_cookie is null, do you think there is a limitation per subscription type when making a webrequest?

**Comment by minhhungit** [comment]
@fabercs : try to change your password to a simple password, like 12345XYZ

**Comment by fabercs** [comment]
This does not make sense, why would i change it? my password is not too complex as well.

**Comment by fabercs** [comment]
@minhhungit you were right, i've just changed it to a simple one and i could login. But i did not undertand why :) Can you or anybody explain it?

**Comment by Ebram-Tharwat** [comment]
@minhhungit , thank you much for your help. I'm wondering why would we need that.

@fabercs , can you share what special/complex letters you used in your password. Or can you try and debug to see what caused the error exactly.

**Comment by fabercs** [comment]
@Ebram-Tharwat firstly, thank you Ebram for this wonderful tool, I was using a password contains characters, it looked like _"Dfgh65++"_, there was not any errors or exceptions response is OK, but if you tell me what variable(s) in response object should i observe to get what is going on, i can do that for you.

**Comment by Ebram-Tharwat** [comment]
@minhhungit @fabercs , I got the issue. When sending a Web Request with special characters, what comes after is trimmed. So, password with value `12&34` becomes `12`.

I will add a commit fixing this issue, but i need to do some testing on it.
