### ISSUE TITLE
Download course subtitles

### ISSUE THREAD

**Issue by Ebram-Tharwat** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#5]
Add an option to download videos' subtitles.

It should simple radio button add to settings page, indicating if subtitles should be downloaded along with course' videos.
Subtitle should be a simple .sub/.srt text files in the same way as in movies' subtitle.

**Comment by nmquan-dev** [comment]
@Ebram-Tharwat Hi, If I want to download the subtitles, I have to adjust in the web.config of each course.
Is there anyway check the course subtitles download it? Thanks for support!!!!

**Comment by Ebram-Tharwat** [comment]
@nmquan-dev , sorry i didn't understand your question, can you please explain it more?

But the current behavior is, if you set `SUBTITLES` in `Web.config` to `true`, then subtitles will be downloaded for **every** course. 
This `ture/false` switch will be applied through the whole application not by course.

**Comment by nmquan-dev** [comment]
Sorry, I understood.
Thanks for supporting

2016-12-10 23:42 GMT+07:00 Ebram-Tharwat <notifications@github.com>:
