### ISSUE TITLE
Broken Courses

### ISSUE THREAD

**Issue by brunnels** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#8]
This one isn't working.  Throwing 429 errors even though others work fine.
https://app.pluralsight.com/library/courses/javascript-fundamentals-es6

This one has special characters that aren't converted on the page.  Probably need to convert to utf8.  I added a converter to the valididateFileName method but haven't fully tested it.  Probably need to do something in the json serializer instead.
https://app.pluralsight.com/library/courses/java-8-data-processing-streams-collectors-optionals

**Comment by brunnels** [comment]
This one errors too
https://app.pluralsight.com/library/courses/typescript

**Comment by brunnels** [comment]
429 errors
https://app.pluralsight.com/library/courses/bootstrap-3

**Comment by Ebram-Tharwat** [comment]
I will check/debug these courses. May add a unit testing for validating course files/folders names.

**Comment by brunnels** [comment]
I may have broken something along too as I could have sworn at least one of
these worked before.  I'm thinking it might be a good idea to move the
cookie getter methods to the Course class and make cookie a property with a
backing field and a clearCookie method.  Then you can use the cookie
property unless there's an error then try clearing the cookie and calling
the property again which would get it a new one.

**Comment by Ebram-Tharwat** [comment]
Are you sure the error is caused by `cookie` not invalid file/folder name ?

I have this course on my machine ([https://app.pluralsight.com/library/courses/javascript-fundamentals-es6](https://app.pluralsight.com/library/courses/javascript-fundamentals-es6)), and I don't recall any error happened during downloading it.

**Comment by Ebram-Tharwat** [comment]
I just noticed you said you get error `429`, which indicate [sending too many requests in a given amount of time](https://httpstatusdogs.com/429-too-many-requests). May be we need to do more trials on `download speed throttling` to make sure it's reliable enough.

**Comment by brunnels** [comment]
Yes,  was 429 but I don't think that was actually the problem as I could
immediately switch to a different course and it would work.  I will deny
when I get a chance

**Comment by brunnels** [comment]
Okay, did some debugging and rewrote the getClip stuff.  Ended up being that some clips aren't available in 1280x720 so it gives 400 bad request.  I'm checking for that now and dropping down to 1024x768

**Comment by brunnels** [comment]
I can confirm the fix is good for all the clips that wouldn't download before.  I'm re-organizing my changes a bit to more most of the logic out of the controllers and into the viewmodels then I'll update my original PR.

**Comment by Ebram-Tharwat** [comment]
Good, I will wait your changes. Thanks for your feedback
