### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by rafalenden** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#9]
Could you please provide a short description how to compile and use this app?

**Comment by Ebram-Tharwat** [comment]
Well, it should be the same you do for any .net web application. Firstly, Read carefully **section [things-to-note](https://github.com/Ebram-Tharwat/CSharp-Pluralsight-Downloader#things-to-note)**, then:

1. Update the configurations in `Web.config`.

1. Hit run, which will restore the `Nuget` packages and start the app.

1. (optional), Debug the app in case of any errors.

@rafalenden , please let me know if this steps are enough or still need more clarifications.
